### PR TITLE
Bump to nixos-21.05

### PR DESCRIPTION
**Pull request by ElvishJerricco**
Enables building on aarch64

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
It's *possible* we can get rid of some of those overrides in haskellPackages, but I didn't test any of that. Should we?

**Comment by ali-abrar** [comment]
> It's _possible_ we can get rid of some of those overrides in haskellPackages, but I didn't test any of that. Should we?

We don't have to do that as part of this change, but good to note.

**Comment by ali-abrar** [comment]
Created #20 to remind us to CI this.

**Comment by ElvishJerricco** [comment]
@ali-abrar Is there a reason this can't be merged?

**Review by Ericson2314 — APPROVED** [review]

**Pull request merged**
